openapi: 3.0.1
info:
  title: Random Number API
  description: API for generating and managing random numbers.
  version: 1.0.0
servers:
  - url: /api
paths:
  /hello:
    get:
      summary: Prints Hello world
      operationId: helloWorld
      tags:
        - hello
      responses:
        200:
          description: The hello world message
          content:
            application/json:
              schema:
                type: string
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: "Message"

  /getRandomNum:
    get:
      summary: Get a random number
      description: Generates a random number based on a predefined random limit.
      operationId: getRandomNum
      responses:
        '200':
          description: A random number generated based on the random limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RandNum'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  /getRandomLimit:
    get:
      summary: Get the random limit
      description: Retrieves the current random limit.
      operationId: getRandomLimit
      responses:
        '200':
          description: The current random limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RandLimit'

components:
  schemas:
    RandNum:
      type: object
      properties:
        num:
          type: integer
          description: The generated random number
          example: 123
    RandLimit:
      type: object
      properties:
        randLimit:
          type: integer
          default: 1000
          description: The limit for the random number generator
          example: 1000
